<?php

return [
    ['name' => 'UEFA Champions League', 'api_id' => 2, 'season' => 2023, 'country' => 'Europe'],
    ['name' => 'Premier League', 'api_id' => 39, 'season' => 2023, 'country' => 'England'],
    ['name' => 'La Liga', 'api_id' => 140, 'season' => 2023, 'country' => 'Spain'],
    ['name' => 'Ligue 1', 'api_id' => 61, 'season' => 2023, 'country' => 'France'],
    ['name' => 'Bundesliga', 'api_id' => 78, 'season' => 2023, 'country' => 'Germany'],
    ['name' => 'Serie A', 'api_id' => 135, 'season' => 2023, 'country' => 'Italy'],
    ['name' => 'Egyptian Premier League', 'api_id' => 233, 'season' => 2023, 'country' => 'Egypt'],
    ['name' => 'Saudi Pro League', 'api_id' => 152, 'season' => 2023, 'country' => 'Saudi Arabia'],
    ['name' => 'Botola Pro', 'api_id' => 200, 'season' => 2023, 'country' => 'Morocco'],
    ['name' => 'Algerian Ligue 1', 'api_id' => 318, 'season' => 2023, 'country' => 'Algeria'],
    ['name' => 'Tunisian Ligue 1', 'api_id' => 213, 'season' => 2023, 'country' => 'Tunisia'],
    ['name' => 'Iraqi Premier League', 'api_id' => 345, 'season' => 2023, 'country' => 'Iraq'],
    ['name' => 'Kuwaiti Premier League', 'api_id' => 304, 'season' => 2023, 'country' => 'Kuwait'],
    ['name' => 'Oman Professional League', 'api_id' => 285, 'season' => 2023, 'country' => 'Oman'],
    ['name' => 'Jordan League', 'api_id' => 257, 'season' => 2023, 'country' => 'Jordan'],
    ['name' => 'UAE Pro League', 'api_id' => 172, 'season' => 2023, 'country' => 'United Arab Emirates'],
    ['name' => 'Syrian Premier League', 'api_id' => 347, 'season' => 2023, 'country' => 'Syria'],
    ['name' => 'Qatar Stars League', 'api_id' => 195, 'season' => 2023, 'country' => 'Qatar'],
    ['name' => 'Primeira Liga', 'api_id' => 94, 'season' => 2023, 'country' => 'Portugal'],
    ['name' => 'Eredivisie', 'api_id' => 88, 'season' => 2023, 'country' => 'Netherlands'],
    ['name' => 'Süper Lig', 'api_id' => 203, 'season' => 2023, 'country' => 'Turkey'],
    ['name' => 'Brasileirão Série A', 'api_id' => 71, 'season' => 2023, 'country' => 'Brazil'],
    ['name' => 'Argentine Primera División', 'api_id' => 128, 'season' => 2023, 'country' => 'Argentina'],
    ['name' => 'Major League Soccer', 'api_id' => 253, 'season' => 2023, 'country' => 'USA/Canada'],
    ['name' => 'UEFA Europa League', 'api_id' => 3, 'season' => 2023, 'country' => 'Europe'],
    ['name' => 'UEFA Europa Conference League', 'api_id' => 848, 'season' => 2023, 'country' => 'Europe'],
    ['name' => 'AFC Champions League', 'api_id' => 9, 'season' => 2023, 'country' => 'Asia'],
    ['name' => 'Africa Cup of Nations', 'api_id' => 6, 'season' => 2023, 'country' => 'Africa', 'type' => 'cup'],
    ['name' => 'CAF Confederation Cup', 'api_id' => 5, 'season' => 2023, 'country' => 'Africa'],
    ['name' => 'FIFA World Cup', 'api_id' => 1, 'season' => 2022, 'country' => 'World', 'type' => 'cup'],
    ['name' => 'Libyan Premier League', 'api_id' => 346, 'season' => 2023, 'country' => 'Libya'],
    ['name' => 'Turkish Cup', 'api_id' => 67, 'season' => 2023, 'country' => 'Turkey', 'type' => 'cup'],
    ['name' => 'Copa Libertadores', 'api_id' => 13, 'season' => 2023, 'country' => 'South America'],
    ['name' => 'Iran Pro League', 'api_id' => 290, 'season' => 2023, 'country' => 'Iran'],
    ['name' => 'A-League', 'api_id' => 188, 'season' => 2023, 'country' => 'Australia'],
    ['name' => 'Allsvenskan', 'api_id' => 29, 'season' => 2023, 'country' => 'Sweden'],
    ['name' => 'Scottish Premiership', 'api_id' => 179, 'season' => 2023, 'country' => 'Scotland'],
    ['name' => 'CAF World Cup Qualifiers', 'api_id' => null, 'season' => 2023, 'country' => 'Africa'],
    ['name' => 'Africa Cup of Nations Qualifiers', 'api_id' => null, 'season' => 2023, 'country' => 'Africa'],
    ['name' => 'CONCACAF Nations League', 'api_id' => 15, 'season' => 2023, 'country' => 'North America'],
    ['name' => 'Gulf Cup', 'api_id' => null, 'season' => 2023, 'country' => 'Gulf'],
    ['name' => 'AFC World Cup Qualifiers', 'api_id' => null, 'season' => 2023, 'country' => 'Asia'],
    ['name' => 'CONCACAF World Cup Qualifiers', 'api_id' => null, 'season' => 2023, 'country' => 'North America'],
    ['name' => 'CONMEBOL World Cup Qualifiers', 'api_id' => 31, 'season' => 2023, 'country' => 'South America'],
    ['name' => 'Egypt League Cup', 'api_id' => null, 'season' => 2023, 'country' => 'Egypt'],
];
